### ISSUE TITLE
TA 2 Checklist

### ISSUE THREAD

**Issue by yogaiw** [yogaiw/rental-kamera#14]
## Naskah / Redaksional
- [x] 'konfirmasi ketersediaan alat' -> 'konfirmasi reservasi alat'
- [x] Membuat dokumen HKI
- [x] Mencari jurnal terkait scoring SUS untuk bidang sistem informasi / web commerce

# Bimbingan
## 22/6/2022
- [x] lengkapi flash messages
- [x] notifikasi melalui email  (done -> https://github.com/yogaiw/kancil-rental/commit/10c94631d17619624796d047076e0a32677f17c6)
- [x] tambah role superuser (done -> https://github.com/yogaiw/kancil-rental/commit/42c9fe96296cfa2a54c5069d2d09a46aa12923e3)

## 27/7/2022
- [x] Pengumpulan data alat
- [x] Iterasi - perubahan diagram dimasukkan lampiran, pada laporan cukup tampilan saja
- [x] Per diagram harus dijelaskan
- [x] Jurnal MIB https://ejurnal.stmik-budidarma.ac.id/index.php/mib

## 3/8/2022
- [x] Jurnal mengenai pertanyaan sus
- [x] Lengkapi BAB II bagian SUS

## 15/8/2022
- [x] finishing naskah

# Diagrams
## Use Case
- [x] Use Case kurang 'Admin mengelola data kategori'
## Activty
- [x] Daftar
- [x] Melihat katalog alat
- [x] Memasukkan alat ke keranjang
- [x] Melakukan checkout
- [x] Upload bukti bayar
- [x] Memeriksa Ketersediaan alat
- [x] Membuat Reservasi (admin)
- [x] Mengkonfirmasi reservasi alat (admin)
- [x] Mengkonfirmasi pengemablian alat (admin)
- [x] Mengkonfirmasi pembayaran (admin)
- [x] Mengelola data alat (owner)
- [x] mengelola admin (owner)
- [x] mengelola data kategori (owner)

## Sequence
- [x] Daftar
- [x] Melihat katalog alat
- [x] Memasukkan alat ke keranjang
- [x] Melakukan checkout
- [x] Upload bukti bayar
- [x] Memeriksa Ketersediaan alat
- [x] Membuat Reservasi (admin)
- [x] Mengkonfirmasi reservasi alat (admin)
- [x] Mengkonfirmasi pengemablian alat (admin)
- [x] Mengkonfirmasi pembayaran (admin)
- [x] Mengelola data alat (owner)
- [x] mengelola admin (owner)
- [x] mengelola data kategori (owner)
